config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'homes/about'=>'homes/about',as: 'about'

  resources :post_books, only: [:new, :index, :show,:create,:destroy] do
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show,:edit,:update] 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post_book
end

app/models/post_book.rb
class PostBook < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy

  validates :title, presence: true, length: {maximum: 100}
  validates :body, presence: true, length: {maximum: 100}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :post_books, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    post_books_path
  end
  
  def after_sign_out_path_for(resource)
    about_path
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    post_book = PostBook.find(params[:post_book_id])
    favorite = current_user.favorites.new(post_book_id: post_book.id)
    favorite.save
    redirect_to post_book_path(post_book)
  end
  
  def destroy
    post_book = PostBook.find(params[:post_book_id])
    favorite = current_user.favorites.find_by(post_book_id: post_book.id)
    favorite.destroy
    redirect_to post_book_path(post_book)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/post_books_controller.rb
class PostBooksController < ApplicationController
  def new
    @post_book = PostBook.new
  end
  
  def create
    @post_book= PostBook.new(post_book_params)
    @post_book.user_id = current_user.id
    if @post_book.save
      redirect_to post_books_path
    else
      render :new
    end
  end

  def index
    @post_books = PostBook.page(params[:page])
  end

  def show
    @post_book = PostBook.find(params[:id])
  end
  
  def destroy
    @post_book = PostBook.find(params[:id])
    @post_book.delete
    redirect_to post_books_path
  end
  
  private

  def post_book_params
    params.require(:post_book).permit(:title, :body, :caption)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @post_books = @user.post_books.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_books_helper.rb
module PostBooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<h1>About</h1>

app/views/homes/top.html.erb
<div>
  <h1>This is shortshort! </h1>
  <p>Tell me a short-short Story!</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shortshort</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Post', new_post_book_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'My Page', user_path(current_user.id), class: 'nav-link text-dark' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "Log in", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>Tell Anyone a shortshort Story</p>
          </div>
          <div class="col-md-8">
            <h6 class="text-white mt-2 mb-3">Link</h6>
            <ul class="p-0 list-unstyled">
              <li>
                <a href="" title="About" class="text-white-50">Company</a>
              </li>
              <li>
                <a href="" title="License informations" class="text-white-50">Policy</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/post_books/index.html.erb
<div class="card-list-container py-5">
  <% @post_books.each do |post_book| %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <div class="card-body">
      <div class="row">
        <div class="col-10">
          <p class="card-title">
            <%= link_to(post_book_path(post_book.id), class:"text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= post_book.title %></span></strong>
            <% end %>
          </p>
          <p class="card-text">Story：<%= post_book.body %></p>
          <span><i class="fas fa-user"></i> By <%= post_book.user.name %> ｜ </span>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <%= paginate @post_books %>
</div>

app/views/post_books/new.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">Let's Create</h5>
      <div class="form-body p-4">
        <% if @post_book.errors.any? %>
          <ul class="alert alert-danger" role="alert">
            <h6 class="alert-heading">
              <%= @post_book.errors.count %> ERROR!
            </h6>
            <% @post_book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @post_book do |f| %>
          <div class="input-group mb-3 mt-4">
            <%= f.text_field :title, class:"form-control", placeholder:"Title" %>
            <%= f.text_area :body, class:"form-control", placeholder:"Story" %>
          </div>
          <hr>
          <%= f.submit 'Post', class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/post_books/show.html.erb
<div>
  <p>UserName：<%= @post_book.user.name %></p>
  <p>Title：<%= @post_book.title %></p>
  <p>Story：<%= @post_book.body %></p>
  <p>Date：<%= @post_book.created_at.strftime('%Y/%m/%d') %></p>
   <% if @post_book.user == current_user %>
    <%= link_to "Delete", post_book_path(@post_book), method: :delete %>
  <% end %>
  
  <% if @post_book.favorited_by?(current_user) %>
    <p>
      <%= link_to post_book_favorites_path(@post_book), method: :delete do %>
        ♥<%= @post_book.favorites.count %> Like
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to post_book_favorites_path(@post_book), method: :post do %>
        ♡<%= @post_book.favorites.count %> Like
      <% end %>
    </p>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>Edit Profile</h2>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <%= f.submit "Save" %>
<% end %>

app/views/users/show.html.erb
<div>
  <h3><%= @user.name %></h3>
  <% if @user == current_user %>
    <p><%= link_to "Profile Edit", edit_user_path(@user)%></p>
  <% end %>
</div>

<!-- ユーザーの投稿一覧 -->

<% @post_books.each do |post_book| %>
<div>
  <p>Title：<%= post_book.title %></p>
  <p>Story：<%= post_book.body %></p>
  <p>Date：<%= post_book.created_at.strftime('%Y/%m/%d') %></p>
</div>
<% end %>
<%= paginate @post_books %>